script/lib.sh, script/lint, script/linter/pkgdoc, tests/fixedbugs/issue50/doc.go
=> linter for package docstrings

README.md, examples/add/README.md, examples/add/asm.go, examples/args/asm.go, examples/complex/asm.go, examples/ext/asm.go, examples/geohash/geohash_test.go, examples/sha1/sha1.go, examples/stadtx/stadtx.go, examples/stadtx/stadtx_test.go, internal/load/tables.go, internal/opcodescsv/analysis_test.go, internal/opcodesxml/opcodesxml_test.go, operand/checks.go, operand/make_const.go, tests/cast/asm.go, tests/fixedbugs/issue50/asm.go, tests/fixedbugs/issue62/asm.go, tests/fixedbugs/issue62/issue62_test.go
Apply @mvdan's opinionated gofumpt formatter across the codebase.
=> all: apply gofumpt

.github/workflows/ci.yml
=> ci: separate lint job

.github/workflows/ci.yml
=> ci: change schedule

pass/cfg.go, pass/cfg_test.go
Add the label in question to the error message.
I am not a huge fan of this error in general, but at least some info would be nice.
=> "instruction should follow a label" info

.github/workflows/ci.yml, tests/thirdparty/config.go, tests/thirdparty/config_test.go, tests/thirdparty/packages.json, tests/thirdparty/packages_test.go
=> tests/thirdparty: add klauspost/compress/s2

tests/thirdparty/packages.json
=> tests/thirdparty: blake3

tests/thirdparty/packages.json
=> tests/thirdparty: lukechampine/us/merkle/blake2b

pass/alloc.go, pass/alloc_test.go
=> pass: support priority in register allocator

.github/workflows/packages.yml, tests/thirdparty/packages.json
=> tests/thirdparty: add segmentio/asm

.github/workflows/packages.yml, tests/thirdparty/packages.json
=> tests/thirdparty: add ericlagergren/lwcrypto

.github/workflows/thirdparty.yml, internal/github/client.go, internal/github/client_test.go, internal/github/models.go, internal/test/utils.go, tests/thirdparty/config.go, tests/thirdparty/config_test.go, tests/thirdparty/metadata_test.go, tests/thirdparty/packages.json
Fetches third-party package metadata from Github.
=> tests/thirdparty: package metadata

.github/workflows/packages.yml, tests/thirdparty/packages.json
=> tests/thirdparty: add filippo.io/edwards25519

.github/workflows/packages.yml, tests/thirdparty/packages.json
=> tests/thirdparty: add lukechampine/blake3

.github/workflows/packages.yml, tests/thirdparty/packages.json
=> tests/thirdparty: re-enable segmentio/asm

.github/workflows/packages.yml, tests/thirdparty/packages.json
=> tests/thirdparty: add github.com/oasisprotocol/deoxysii

.github/workflows/ci.yml, .github/workflows/packages.yml, .github/workflows/stress.yml, .github/workflows/thirdparty.yml, tests/thirdparty/make_workflow.go
=> .github: upgrade setup-go action

.github/workflows/packages.yml, tests/thirdparty/projects.json
=> tests/thirdparty: add klauspost/compress/zstd

.github/workflows/packages.yml, README.md, doc/adopters.md, tests/thirdparty/projects.json
=> tests/thirdparty: add cloudflare/circl

.github/workflows/pr.yml
=> .github: fix automerge

README.md, internal/cmd/docgen/main.go, internal/cmd/docgen/templates/readme.tmpl
Use the `k` format for thousands, just like Github itself.
=> doc: format stars count

.golangci.yml, attr/make_textflag.go, buildtags/buildtags.go, gotypes/components.go, internal/cmd/docgen/main.go, internal/inst/table_test.go, internal/opcodesxml/opcodesxml.go, internal/stack/stack_test.go, internal/test/utils.go, script/bootstrap
=> all: upgrade to golangci-lint v1.49.0

README.md, internal/cmd/docgen/templates/readme.tmpl
=> doc: fix ci badge
