- build/pseudo.go
- operand/checks.go
- reg/collection.go
- reg/reg_test.go
- reg/types.go
It was pointed out #73 that `Bytes()` is a poor name for the size of the register in bytes. In idiomatic Go you would probably expect a `Bytes()` method to return `[]byte`.
This diff changes the `Bytes()` to `Size()`. As a result the `Size` type also needed to be renamed, and `Width` seemed a reasonable choice.
> reg: rename Bytes() to Size()

- gotypes/components.go
- gotypes/components_test.go
Issue #77 pointed out that in the case of named array types, the `gotypes` Components type fails to recognize the underlying type as an array. In fact this problem was more widespread. This diff fixes the missing calls to `Underlying()` and adds some test cases.
> gotypes: add missing Underlying() calls

- build/context.go
- gotypes/signature_test.go
> lint: stop using deprecated go/packages api

- internal/prnt/printer.go
Before printing a comment, remove trailing whitespace.
Generation would output `// ` for empty comments.
So we trim the whitespace off the end before printing.
> Trim trailing comment whitespace

- pass/pass.go
- pass/verify.go
- pass/verify_test.go
Introduces a pass to verify memory operands. This is added to a new
Verify pass, that in future could do much more.
Closes #125
> pass: VerifyMemOperands

- build/global.go
Full disclosure: my motivation here is to hack AVX-512 into my `avo` codegen by defining custom `ir.Instruction`s... 😬
> Expose Instruction method on global context

- reg/collection.go
- reg/reg_test.go
- reg/x86.go
Here's the result of a couple of hours of work learning how the register allocation code works and implementing the AVX512 opmask registers within the existing framework as I understand it. So this is a proposed stepping stone towards https://github.com/mmcloughlin/avo/issues/20
@lukechampine If merged, this code should also remove the need for you to define and explicitly manage opmask registers as in this code: 
https://github.com/lukechampine/blake3/blob/59a82aea36b67f99eb83ea2d12bb378392e234a1/avo/gen.go#L543-L545
The only real question I had with this code is how to properly account for the special treatment of the K0 register in AVX512.
My understanding from the Intel docs is that K0 is a real register just like K1-K7, and can be used for memory operations and to hold constants or …
> Added support for AVX512 opmask registers (K0-K7)

- internal/cmd/avogen/main.go
- internal/gen/gen.go
This makes it easier to debug avogen:
When you emit invalid syntax,
you can inspect the generated file to determine
what went wrong, instead of having only
gofmt's error to work with.
Signed-off-by: Josh Bleecher Snyder <josharian@gmail.com>
> internal/cmd/avogen: write output file even when gofmt fails

- examples/dot/dot_test.go
- examples/geohash/geohash_test.go
- go.mod
- go.sum
Add necessary feature checks to the `dot` and `geohash` examples to prevent illegal instruction errors.
Fixes #170 #153
> examples: cpu feature checks

- operand/checks.go
- operand/checks_test.go
This has been such a great library for us! But we've been working around an issue concerning immediates that this PR should address. Many of the instruction functions correctly match the size of immediate values, but they only accept unsigned immediates. For example:
```go
r := GP64()
ANDQ(I8(-32), r)   // ANDQ: bad operands
```
While the `imm8` input is checked as expected, the `operand.IsIMM8()` function is causing this check to incorrectly fail.
I believe this PR should address issue #181
> Allow signed immediates to be matched by IsIMMX functions

- .github/workflows/ci.yml
Following advice in briansmith/untrusted#50.
> ci: github actions hardening

- buildtags/syntax.go
```
$ ./tmp/testgo161718.sh ./buildtags/ ./printer/
+ go1.16.8 test ./buildtags/ ./printer/
ok  	github.com/mmcloughlin/avo/buildtags	0.001s
ok  	github.com/mmcloughlin/avo/printer	0.002s
+ go1.17.2 test ./buildtags/ ./printer/
ok  	github.com/mmcloughlin/avo/buildtags	0.001s
ok  	github.com/mmcloughlin/avo/printer	0.002s
+ gotip test ./buildtags/ ./printer/
ok  	github.com/mmcloughlin/avo/buildtags	0.001s
ok  	github.com/mmcloughlin/avo/printer	0.002s
```
Updates #183
> buildtags: Format only go:build lines for go 1.18+

- build/global.go
Exposes a few functions on `Context` that are not available globally. This
oversight suggests that #33 or #133 would be reasonable.
> build: global Function() and SignatureExpr()

- tests/thirdparty/packages_test.go
When trying to add a test case from the standard library, cloning golang/go
was taking forever. This PR switches to a shallow clone.
> tests/thirdparty: use shallow clone

- .github/release.yml
`cadobot` generates many uninteresting commits. Exclude them from the
auto-generated release notes generated by Github.
Reference:
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
> .github: exclude bot commits from auto-generated release notes

- internal/load/load.go
- internal/load/tables.go
- internal/opcodesextra/instructions.go
- internal/opcodesextra/movlqzx.go
> internal/opcodesextra: curated extra instructions

- .github/workflows/packages.yml
- .github/workflows/thirdparty.yml
- tests/thirdparty/config.go
- tests/thirdparty/packages_test.go
- tests/thirdparty/suite.json
> tests/thirdparty: add crypto/internal/bigmod

- .github/actions/create-pull-request/action.yml
Many bot commits have landed with an incorrectly templated author name, for example 67039b7ed96f015818f68be22f009bd9b6ed910d has:
```
Co-authored-by: {{ steps.bot.outputs.login }} <104697117+cadobot[bot]@users.noreply.github.com>
```
This PR fixes the bad template.
> .github/actions: fix bot author template

- script/bootstrap
Updates `golangci-lint` install to incorporate the fix for golangci/golangci-lint#3509, which was affecting CI tests, for example:
https://github.com/mmcloughlin/avo/actions/runs/4030013813
> script: fix golangci-lint install

- script/bootstrap
This reverts commit b2ed9c77ec7510920d49dd882bc03735dfe9b774.
It seems Github fixed the underlying issue:
https://github.com/orgs/community/discussions/45590#discussioncomment-4802887
> Revert "script: fix golangci-lint install (#368)"

- .github/workflows/ci.yml
- .github/workflows/metadata.yml
- .github/workflows/stress.yml
- script/bootstrap
No longer required given updates to `actions/setup-go`.
> ci: remove "Configure Go Environment" step

- .github/workflows/packages.yml
- tests/thirdparty/suite.json
The Go third-party compatibility tests were pinned to the release candidate version. This change uses the now official Go 1.20.1 release tag.
> tests/thirdparty: update golang/go tests to go1.20.1

- .github/workflows/pr.yml
In contributor PRs such as #372 we see that the pr/autoland job fails due to permissions issues obtaining an app token from a fork.
This job is actually only required to auto-land bot PRs. Instead of skipping just the auto-land setting step, we should be skipping the entire thing.
Fixes #381
> ci: skip entire autoland job for non-bot users

- .github/workflows/ci.yml
- .github/workflows/deps.yml
- .github/workflows/metadata.yml
- .github/workflows/packages.yml
- .github/workflows/stress.yml
- .github/workflows/thirdparty.yml
- tests/thirdparty/make_workflow.go
- .github: bump to go 1.21
- tests/thirdparty: update workflow generator to 1.21
> ci: bump to go 1.21

- .golangci.yml
- build/context.go
- build/global.go
- gotypes/components.go
- internal/cmd/docgen/main.go
- internal/github/client.go
- internal/prnt/printer.go
- operand/checks_test.go
- pass/cfg_test.go
Enable the `use-any` `revive` rule which requires replacing the empty
interface `interface{}` with `any`.
> all: enable use-any revive rule

- .github/workflows/packages.yml
- README.md
- doc/adopters.md
- tests/thirdparty/suite.json
Adds the https://github.com/bytedance/gopkg `xxhash3` package to the
third-party test suite.
> tests/thirdparty: add bytedance/gopkg

- .github/workflows/packages.yml
- tests/thirdparty/suite.json
Add the `huff0` package from the `github.com/klauspost/compress` module to the third-party test suite.
https://github.com/klauspost/compress/tree/v1.17.5/huff0/_generate
Upgrade the version of `github.com/klauspost/compress` under test to
`v1.17.5`.
Closes #421
> tests/thirdparty: add github.com/klauspost/compress/huff0
